Document: inviteflood
Title: Debian inviteflood Manual
Author: <insert document author here>
Abstract: This manual describes what inviteflood is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/inviteflood/inviteflood.sgml.gz

Format: postscript
Files: /usr/share/doc/inviteflood/inviteflood.ps.gz

Format: text
Files: /usr/share/doc/inviteflood/inviteflood.text.gz

Format: HTML
Index: /usr/share/doc/inviteflood/html/index.html
Files: /usr/share/doc/inviteflood/html/*.html
